### PR TITLE
set up epel repo before pulling atop from it

### PR DESCRIPTION
**Pull request by dannenberg**

### CODE REVIEW

**Comment by dannenberg** [comment]
though this doesnt help your cookbook be os agnostic...

**Comment by keyan** [comment]
What if we did:

```
if platform_family?('rhel')
  conf_file_location = '/etc/sysconfig/atop'
  template_source = 'atop-rhel.erb'

  include_recipe 'yum-epel'
elsif platform_family?('debian')
  conf_file_location = '/etc/default/atop'
  template_source = 'atop-debian.erb'

  <SOMETHING?>
else
  Chef::Application.fatal!('Unsupported operating system', 1)
end

package 'atop' do
  action node['atop']['action']
  version node['atop']['version']
end
```

**Comment by dannenberg** [comment]
gotta change the dependencies in metadata.rb and add an apt equivalent to the current yum package

**Comment by dannenberg** [comment]
keyan,
it is with a heavy heart that i'm reaching out and closing this pull request. over the years, it has become quite clear to me that you do not appreciate my contributions and never will. i hope your new life in seattle finds you well.
sincerely,
dannenberg

PS i dont know if this is publicly visible so i feel i need to clarify in this post script that this is a joke in case some rando sees it.

**Pull request closed without merging**
